---
title: "midterm project sports analytics"
author: "Logan Schafer"
date: "2023-10-22"
output: html_document
---
## The majority of this code is cleaning to get ready for analysis. 
```{r}
library(tidyverse)
library(dplyr)
```


```{r}
gamedata <- read.csv("GAME.csv")
```

```{r}
teamdata <- read.csv("TEAM.csv")
```


```{r}
##Removing random blank rows for team data 
cleanedteam <- teamdata[rowSums(is.na(teamdata)) <= 15 ,  ]
```

```{r}
##Creating subset of teams 
cleanteam <- cleanedteam[cleanedteam$gid >=3456 & cleanedteam$gid <= 4790, ]
```

```{r}
##Subetting columns needed for team data 
cleanteamfin <- cleanteam[c(2,3,4,12,14,20,29,30,37,38,41,45)]
```


```{r}
## creating home and away subsets of team data 
visitor_teams <- cleanteamfin %>%
  filter(row_number() %% 2 == 1)
home_teams <- cleanteamfin %>%
  filter(row_number() %% 2 == 0)
```

```{r}
## Creating rename function for home teams 
rename_columns <- function(names) {
  names <- ifelse(names %in% c("gid"), names, paste0("h_", names))
  names
}
```

```{r}
## Creating rename function for away teams 
rename_columns2 <- function(names) {
  names <- ifelse(names %in% c("gid"), names, paste0("v_", names))
  names
}
```

```{r}
##Applying rename to home teams 
home_teams <- home_teams %>%
  rename_with(.cols = everything(), .fn = ~rename_columns(.))
```

```{r}
##Applying rename to visitor teams 
visitor_teams <- visitor_teams %>%
  rename_with(.cols = everything(), .fn = ~rename_columns2(.))
```

```{r}
##Putting these two subsets togethor for full team data 
merged_team <- left_join(home_teams, visitor_teams, by = "gid")
```

```{r}
merged_team$h_ty = merged_team$h_ry + merged_team$h_py
merged_team$v_ty = merged_team$v_ry + merged_team$v_py
```


```{r}
View(merged_team)
```


```{r} 
##Removing random blank rows 
cleanedgame <- gamedata[rowSums(is.na(gamedata)) <= 6 ,  ] 
```

```{r}
##Creating total points column 
cleanedgame$TotalPoints = cleanedgame$ptsv + cleanedgame$ptsh
```

```{r}
##Creating over/under classifier 
cleanedgame$ouc <- ifelse(cleanedgame$ou > cleanedgame$TotalPoints, "under", "over")
cleanedgame$ouc_d <- ifelse(cleanedgame$ouc == "over", 1, 0)
```



```{r}
##Creating subset of seasons 
cleangame <- cleanedgame[cleanedgame$seas >= 2013 & cleanedgame$seas <= 2017, ]
```

```{r}
##Removing all rows without temperature that aren't dome or close roof took data points down from 1335 to 1324
cleangame1 <- cleangame[!(is.na(cleangame$temp) & !(cleangame$cond %in% c("Dome", "Closed Roof"))), ]
```

```{r}
##Removing all rows without humidity that aren't dome or close roof took data points down from 1324 to 1297
cleangame2 <- cleangame1[!(is.na(cleangame1$humd) & !(cleangame1$cond %in% c("Dome", "Closed Roof"))), ]
```

```{r}
##Removing all rows without windspeed that aren't dome or close roof took data points down from 1297 to 1293
cleangame3 <- cleangame2[!(is.na(cleangame2$wspd) & !(cleangame2$cond %in% c("Dome", "Closed Roof"))), ]
```

```{r}
## adding total spread variable 
cleangame$TotalSpread = abs(cleangame$sprv)
```

```{r}
##Removing all uneeded columns
cleangame4 <- cleangame3[, !(names(cleangame3) %in% c("wdir", "ptsv", "ptsh", "sprv"))]
```

```{r}
##Removing all rows without a condition took data from 1293 to 1289
cleangame5 <- cleangame4[cleangame4$cond != "", ]
```

```{r}
##Putting game and team data together
game_team_data <- left_join(cleangame, merged_team, by = "gid")
```

```{r}
##Creating week variable for home and visitor 
game_team_data$t_wk = game_team_data$wk
```

```{r}
## Creating points allowed variable 
game_team_data$h_ptsall <- game_team_data$v_pts
game_team_data$v_ptsall <- game_team_data$h_pts
```

```{r}
## Creating redzone td rate variable 
game_team_data$h_rztr <- game_team_data$h_rzc / game_team_data$h_rza

game_team_data$v_rztr <- game_team_data$v_rzc / game_team_data$v_rza
```

```{r}
## Creating long play touchdown variable 
game_team_data$h_ltd <- game_team_data$h_td - game_team_data$h_rzc

game_team_data$v_ltd <- game_team_data$v_td - game_team_data$v_rzc
```



```{r}
## Creating subset for 2013
subset2013 <- game_team_data[game_team_data$seas == 2013, ]
```


```{r}
##Lagging all home to home point values across all seasons 

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$hpp[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$h_pts[1]
      }
      
      else {
    game_team_data$h_previous_points[game_team_data$seas == seas & 
         game_team_data$wk == current_wk & 
   game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all home to visitor point values across all seasons to populate home field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$hpp[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
      
      else {
   #  game_team_data$h_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all visitor to visitor point values across all seasons

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$vpp[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$v_pts[1]
      }
      
      else {
    game_team_data$v_previous_points[game_team_data$seas == seas & 
         game_team_data$wk == current_wk & 
   game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
        
```


```{r}
##Lagging all visitor to home point values across all seasons to populate visitor field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$vpp[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
```

```{r}
##Lagging all home to home point allowed values across all seasons 

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$hppa[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$h_ptsall[1]
      }
      
      else {
   #  game_team_data$hppa[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ptsall[1]
      }
    }
  }
}
```


```{r}
##Lagging all home to visitor point allowed values across all seasons to populate home field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$hppa[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ptsall[1]
      }
      
      else {
   #  game_team_data$h_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all visitor to visitor point allowed values across all seasons

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$vppa[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$v_ptsall[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
        
```


```{r}
##Lagging all visitor to home point allowed values across all seasons to populate visitor field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$vppa[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_ptsall[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
```

```{r}
##Lagging all home to home time of possesion values across all seasons 

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$htop[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$h_top[1]
      }
      
      else {
   #  game_team_data$hppa[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ptsall[1]
      }
    }
  }
}
```


```{r}
##Lagging all home to visitor time of possession values across all seasons to populate home field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$htop[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_top[1]
      }
      
      else {
   #  game_team_data$h_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all visitor to visitor time of possesion values across all seasons

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$vtop[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$v_top[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
        
```


```{r}
##Lagging all visitor to home time of possesion values across all seasons to populate visitor field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$vtop[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_top[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}

```

```{r}
##Lagging all home to home punt values across all seasons 

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$hpu[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$h_pu[1]
      }
      
      else {
   #  game_team_data$hppa[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ptsall[1]
      }
    }
  }
}
```


```{r}
##Lagging all home to visitor punt values across all seasons to populate home field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$hpu[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pu[1]
      }
      
      else {
   #  game_team_data$h_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all visitor to visitor punt values across all seasons

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$vpu[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$v_pu[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
        
```


```{r}
##Lagging all visitor to home punt values across all seasons to populate visitor field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$vpu[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pu[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}

```

```{r}
##Lagging all home to home redzone rate values across all seasons 

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$hrztr[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$h_rztr[1]
      }
      
      else {
   #  game_team_data$hppa[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ptsall[1]
      }
    }
  }
}
```


```{r}
##Lagging all home to visitor redzone rate values across all seasons to populate home field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$hrztr[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_rztr[1]
      }
      
      else {
   #  game_team_data$h_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all visitor to visitor redzone rate values across all seasons

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$vrztr[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$v_rztr[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
        
```


```{r}
##Lagging all visitor to home redzone rate values across all seasons to populate visitor field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$vrztr[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_rztr[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}

```

```{r}
##Lagging all home to home long touchdowns values across all seasons 

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$hltd[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$h_ltd[1]
      }
      
      else {
   #  game_team_data$hppa[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ptsall[1]
      }
    }
  }
}
```


```{r}
##Lagging all home to visitor long touchdown values across all seasons to populate home field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$hltd[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ltd[1]
      }
      
      else {
   #  game_team_data$h_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all visitor to visitor long touchdowns values across all seasons

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$vltd[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$v_ltd[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
        
```


```{r}
##Lagging all visitor to home long touchdown values across all seasons to populate visitor field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$vltd[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_ltd[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}

```

```{r}
##Lagging all home to home rush yard values across all seasons 

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$hry[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$h_ry[1]
      }
      
      else {
   #  game_team_data$hppa[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ptsall[1]
      }
    }
  }
}
```


```{r}
##Lagging all home to visitor rush yard values across all seasons to populate home field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$hry[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ry[1]
      }
      
      else {
   #  game_team_data$h_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all visitor to visitor rush yard values across all seasons

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$vry[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$v_ry[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
        
```


```{r}
##Lagging all visitor to home rush yard values across all seasons to populate visitor field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$vry[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_ry[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}

```

```{r}
##Lagging all home to home pass yard values across all seasons 

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$hpy[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$h_py[1]
      }
      
      else {
   #  game_team_data$hppa[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_ptsall[1]
      }
    }
  }
}
```


```{r}
##Lagging all home to visitor pass yard values across all seasons to populate home field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$h_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$h_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$hpy[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_py[1]
      }
      
      else {
   #  game_team_data$h_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$h_tname == subset_year$h_tname[i]] <- matching_row$v_pts[1]
      }
    }
  }
}
```


```{r}
##Lagging all visitor to visitor pass yard values across all seasons

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$v_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$v_tname[1]) 
        {
     game_team_data$vpy[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$v_py[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}
        
```


```{r}
##Lagging all visitor to home pass yard values across all seasons to populate visitor field

unique_years <- unique(game_team_data$seas)

# Loop through each unique year and populate 'h_previous_points' in the original dataset
for (seas in unique_years) {
  # Subset the data for the current year
  subset_year <- game_team_data[game_team_data$seas == seas, ]
  
  # Loop through each row within the current year and populate 'h_previous_points'
  for (i in 1:nrow(subset_year)) {
    current_wk <- subset_year$wk[i]
    t_wk <- current_wk - 1
    
    # Find the row with the matching 't_wk', 'h_tname', and 'year' in the original dataset
    matching_row <- game_team_data[game_team_data$seas == seas & 
     game_team_data$wk == t_wk & 
              game_team_data$h_tname == subset_year$v_tname[i], ]
    
    # Assign the value from 'h_pts' or 'v_pts' based on 'h_tname' and 'v_tname' matching
    if (nrow(matching_row) > 0) {
      
      if (subset_year$v_tname[i] == matching_row$h_tname[1]) 
        {
     game_team_data$vpy[game_team_data$seas == seas &        game_team_data$wk == current_wk & 
         game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_py[1]
      }
      
      else {
   #  game_team_data$v_previous_points[game_team_data$seas == seas & 
   #       game_team_data$wk == current_wk & 
   # game_team_data$v_tname == subset_year$v_tname[i]] <- matching_row$h_pts[1]
      }
    }
  }
}

```

```{r}
View(game_team_data)
```


```{r}
##Creating model dataset
OU_data <- game_team_data[c(1:10,12,13,14,20, 21,53:68)]
```

```{r}
View(OU_data1)
```

```{r}
##Removing n/a values for byes and week 1's from each season, went from 1335 to 1086
OU_data1 <- OU_data[complete.cases(OU_data[, c("hpp", "vpp")]), ]
```

```{r}
##Removing all playoff games, went from 1086 to 1051
OU_data2 <- OU_data1[OU_data1$wk <= 17, ]
```

```{r}
OU_data2$tpu <- OU_data2$hpu + OU_data2$vpu
OU_data2$cpp <- OU_data2$hpp + OU_data2$vpp
```

```{r}
##Removing all games that have n/a for redzone efficiency for one potential model, went from 1051 to 997
OU_data2_RZ <- OU_data2[complete.cases(OU_data2[, c("hrztr", "vrztr")]), ]
```

```{r}
##Taking subset with all dome or closed roof games, 256 entries
OU_data_close <- OU_data2[OU_data2$cond %in% c("Dome", "Closed Roof"), ]
```

```{r}
##Taking subset with all outside games, 795 entries
OU_data_open <- OU_data2[!(OU_data2$cond %in% c("Dome", "Closed Roof")), ]
```

```{r}
##Removing outside data without temp, or hum, or winspd, went from 795 to 757
OU_data_open1 <- OU_data_open[complete.cases(OU_data_open[, c("temp", "humd", "wspd")]), ]
```

```{r}
full_model_open = glm( ouc_d ~ day + temp + humd + wspd + cond + surf +  TotalSpread + hpp + vpp + hppa + vppa + htop + vtop + hpu + vpu + hltd + vltd + hry + vry + hpy + vpy  , data = OU_data_open1, family = "binomial")
```

```{r}
summary(full_model_open)
```

```{r}
full_model_close = glm( ouc_d ~ day + surf + TotalSpread + hpp + vpp + hppa + vppa + htop + vtop + hpu + vpu + hltd + vltd + hry + vry + hpy + vpy  , data = OU_data_close, family = "binomial")
```

```{r}
summary(full_model_close)
```

```{r}
full_model_all = glm( ouc_d ~ day + temp + humd + wspd + cond + surf +  TotalSpread +  cpp + hppa + vppa + htop + vtop + tpu + hltd + vltd + hry + vry + hpy + vpy, data = OU_data2, family = "binomial")
```

```{r}
summary(full_model_all)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

